server:
  port: 29081

spring:
  datasource:
    url: jdbc:mysql://120.46.205.217:3306/blog_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    username: ~
    password: root

logging:
  level:
    com.flybearblog.blogserve: trace

blog:
  jwt:
    secret-key: ajkfvp9734IU238dmadslkjRWLIUFASDMHkjlfdsakfl
  authenticate:
    duration-in-minute: 10080