server:
  port: 29081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu_tea_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    username: ~
    password: ~

logging:
  level:
    cn.tedu.tmall: trace

tmall:
  jwt:
    secret-key: ajkfvp9734IU238dmadslkjRWLIUFASDMHkjlfdsakfl
  authenticate:
    duration-in-minute: 10080